package com.io.reset;

import com.io.Main;

import java.io.File;

public class deleteFile {
    public static void main(String[] args) {
        File profileFile = new File(Main.profilePath);
        profileFile.delete();
        System.out.println("If the file was generated by the program then it would be deleted");

    }
}
