package com.io;

import java.io.FileInputStream;
import java.io.FileOutputStream;

public class Main {
    public final static String profilePath = "profile.txt";

    public static void main(String[] args) {
        try {
            FileOutputStream ProfileOut = new FileOutputStream(profilePath);
            String line1 = "----------------------------------\nHello, Welcome to my profile, My name is Arpit and I am a Java Developer \n";
            String line2 = "My github profile : https://github.com/SimformArpit \n\n";
            String line3 = "----------------------------------\nThis file is generated by the java Program";
            byte bLine1[] = line1.getBytes();
            byte bLine2[] = line2.getBytes();
            byte bLine3[] = line3.getBytes();
            ProfileOut.write(bLine1);
            ProfileOut.write(bLine2);
            ProfileOut.write(bLine3);
            ProfileOut.flush();
            ProfileOut.close();
            FileInputStream ProfileIn = new FileInputStream(profilePath);
            int tempProfile = ProfileIn.read();
            while (tempProfile != -1) {
                System.out.print((char) tempProfile);
                tempProfile = ProfileIn.read();
            }
            ProfileIn.close();
        } catch (Exception e) {
            System.out.println(e.getStackTrace());
        }
    }
}